### PR TITLE
website

### PR DESCRIPTION
**Pull request by abhinavmaharana**
Just made a website version of your project using TensorFlow js. The site is not styled so I will make it by tomorrow and send it here. The model in this website is trained for 300 images right now I will increase it with the dataset we have right now.

The dataset trained in these model was trained in teachable machine. The model link is already their in the sketch file if you just copy it and paste in web browser it will show the data.
Here is the link which is uploaded in my drive
https://drive.google.com/file/d/18D0C8YKEXckJoD8HLQ0CRylattIHrne8/view?usp=drivesdk

here is the dataset link
https://teachablemachine.withgoogle.com/models/B8lricL0F/

### CODE REVIEW

**Comment by chandrikadeb7** [comment]
@abhinavmaharana Please use the dataset uploaded here. Update the PR.

**Comment by abhinavmaharana** [comment]
The dataset is uploaded using teachable machine which is uploaded in cloud

**Comment by chandrikadeb7** [comment]
> The dataset is uploaded using teachable machine which is uploaded in cloud.
> 
> https://drive.google.com/file/d/18D0C8YKEXckJoD8HLQ0CRylattIHrne8/view?usp=drivesdk here is the drive link .

Make the files in a complete separate new folder

**Comment by abhinavmaharana** [comment]
Okay I will make the whole new web version then send it again

**Pull request closed without merging**
