### PR TITLE
Redme file Award 

### PR DESCRIPTION
**Pull request by vilsi12**
In Redme file Award and appreciation

### CODE REVIEW

**Comment by chandrikadeb7** [comment]
@vilsi12 In Awards section put the image for ICE project fair. In appreciation section put others. Remove ‘as project maintainer’ part. Keep these sections below Contributions. 

Please make a separate branch for your changes.

**Comment by vilsi12** [comment]
Award

**Comment by vilsi12** [comment]
Hello I have change what you told

**Comment by chandrikadeb7** [comment]
@vilsi12 please make a separate branch for the changes and not master. And add the links for various organisations like devscript, script and student code in not just plain text. Rest all good. Closing this PR. Make a new branch with the changes and raise a new PR. thanks!

**Comment by vilsi12** [comment]
i have done please check i have insert link

**Pull request closed without merging**
