### PR TITLE
Added Notification pop-up

### PR DESCRIPTION
**Pull request by Aayush-hub**
## Added a notification pop-up when no mask is detected in the frame , so that admin became aware of it. Also added github actions to greet first time contributors to this project.

Fixes: #88 Add Notification pop-up system when 'No Mask' detected.

### Screenshot
Capture_output

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@chandrikadeb7 Mam, please review my PR ,so that I can solve more issues and come up with a new PR. #SWOC

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 Mam, please review my PR ,so that I can solve more issues and come up with a new PR. #SWOC

I’ll review it tomorrow. You can pick up new issues

**Comment by Aayush-hub** [comment]
@chandrikadeb7 Fixed 2 issues. @SWOC

**Comment by chandrikadeb7** [comment]
@Aayush-hub Create separate PRs

**Comment by Aayush-hub** [comment]
@chandrikadeb7 Okay mam, done with the changes, please review this PR

**Comment by chandrikadeb7** [comment]
@Aayush-hub Take recent pull and make a fresh PR.

**Pull request closed without merging**
