### PR TITLE
Created an MIT License for Face-Mask-Detection

### PR DESCRIPTION
**Pull request by shubhraagarwal**

### CODE REVIEW

**Comment by chandrikadeb7** [comment]
@shubhraagarwal Delete the existing license.txt file and generate a new MIT License from the templates. Please don't change the readme file.

**Comment by shubhraagarwal** [comment]
Ok. I didn't change the readme file.

**Review by chandrikadeb7 — APPROVED** [review]

**Comment by chandrikadeb7** [comment]
Is this PR for SWOC or DWOC?

**Comment by shubhraagarwal** [comment]
@chandrikadeb7 DWOC

**Pull request merged**
