### PR TITLE
feat: raspberry pi setup instruction

### PR DESCRIPTION
**Pull request by vinamramunot-tech**
#### Issue Number
ISSUE #117 

#### Describe the changes you've made

Created this pull request to setup this project on a Raspberry Pi (IoT device)

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

***NA***

#### Test plan (OPTIONAL)

Follow the setup and run the following commands to setup the project on a raspberry pi

#### Checklist

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by vinamramunot-tech** [comment]
@chandrikadeb7 Not sure why the greeting failed

**Comment by chandrikadeb7** [comment]
@vinamramunot-tech Please don't change requirements.txt file

**Comment by vinamramunot-tech** [comment]
@chandrikadeb7 I have removed the requirements.txt file from this PR. Please let me know this is okay.

**Comment by chandrikadeb7** [comment]
@vinamramunot-tech Make new PR as requirements.txt file is deleted.

**Pull request closed without merging**
